-- MySQL Script generated by MySQL Workbench
-- Mon Apr 30 17:43:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema databases
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema databases
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `databases` DEFAULT CHARACTER SET utf8 ;
USE `databases` ;

-- -----------------------------------------------------
-- Table `databases`.`type_of_settlement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databases`.`type_of_settlement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_of_settlement` VARCHAR(127) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_of_settlement_UNIQUE` (`type_of_settlement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databases`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databases`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(127) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databases`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databases`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(127) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_region_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_region_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `databases`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databases`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databases`.`district` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(127) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_district_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_district_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `databases`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databases`.`locality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databases`.`locality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type_of_settlement_id` INT NOT NULL,
  `district_id` INT NULL DEFAULT -,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locality_type_of_settlement1_idx` (`type_of_settlement_id` ASC),
  INDEX `fk_locality_district1_idx` (`district_id` ASC),
  INDEX `fk_locality_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_locality_type_of_settlement1`
    FOREIGN KEY (`type_of_settlement_id`)
    REFERENCES `databases`.`type_of_settlement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locality_district1`
    FOREIGN KEY (`district_id`)
    REFERENCES `databases`.`district` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locality_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `databases`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
